apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc
  name: mc
spec:
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
      - image: testimage
        name: mc
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 1
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        tolerationSeconds: 10
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        tolerationSeconds: 10
