apiVersion: v1
kind: Service
metadata:
  name: argotest
  namespace: template
spec:
  ports:
  - name: http
    port: 81
    protocol: TCP
    targetPort: 80
  selector:
    app: argotest
  type: NodePort
